### ISSUE TITLE
CSS 알고 싶은 것

### ISSUE THREAD

**Issue by daybrush** [younkue/css#2]
## 기본 CSS 속성
* position
  - static
  - relative
  - absolute
  - fixed
  - sticky
* left, right, top, bottom
* opacity
* filter
* display
  - none
  - block
  - inline-block
  - inline
  - table
  - table-cell
  - table-row
  - flex
  - .....
* border-radius
* clip

## CUSTOM UI
* appearance
* checkbox, radiobox
* progressbar
* input

## Transform
* transform-origin
* ~~matrix~~
* 2D transform
* 3D transform

## CSS Shape
https://github.com/younkue/css/issues/1

**Comment by jbee37142** [comment]
sass ?

**Comment by jbee37142** [comment]
- 효율적인 CSS 작성
- CSS Methology
