### ISSUE TITLE
3주차 수직정렬

### ISSUE THREAD

**Issue by daybrush** [younkue/css#6]
[verticalalign.pdf](https://github.com/younkue/css/files/1853162/verticalalign.pdf)

**Comment by daybrush** [comment]
vertical-align: middle;

**Comment by daybrush** [comment]
vertical-align: baseline;

**Comment by jbee37142** [comment]
vertical-align은 내부에 text가 있을 경우와 없을 경우가 다르다.
있을 경우, text 기준으로 baseline을 정하고,
없을 경우, 상위 엘리먼트의 baseline을 정한다.

**Comment by daybrush** [comment]
baseline
<img width="530" alt="2018-03-28 2 16 36" src="https://user-images.githubusercontent.com/3433062/38010136-aa308000-3292-11e8-96d6-4e818eaecd5d.png">
